services:
  bot:
    build: .
    volumes:
      - "./downloads:/app/downloads"
      - "./config.yaml:/app/config.yaml"
    restart: unless-stopped # restart the bot if it crashes

  postgres:
      image: postgres:13.3-alpine
      environment:
          POSTGRES_USER: downly
          POSTGRES_PASSWORD: downly
          POSTGRES_DB: downly
      volumes:
          - "./postgres-data:/var/lib/postgresql/data"
      restart: unless-stopped # restart the postgres if it crashes