downly:

  app_name: "downly"

  # telegram api configs, get your own config by visiting http://my.telegram.org/
  telegram:
    api_id: ""
    api_hash: ""

    bot_token: "" # telegram bot token, get your own bot token by visiting @BotFather

  # downly bot configs
  configs:
    owner: "" # telegram bot owner userid
    channel_id: "" # telegram channel id
    public: "true" # downly making enabling for public use, false will make only for an owner only
    cobalt_base_url: "https://api.cobalt.meanii.dev" # cobalt base url

  # database configs
  database:
    postgres_url: "postgresql://downly:downly@localhost:5432/downly" # postgres url
    redis_url: "redis://localhost:6379" # redis url