downly:

  namespace: "production"
  app_name: "downly"

  telegram:
    api_id: ""
    api_hash: ""
    bot_token: ""

  configs:
    owner: ""
    channel_id: ""

  database:
    postgres_url: "postgresql://downly:downly@localhost:5432/downly"

  worker:
    numbers_of_workers: 2
    poll_interval_sec: 3
    work_dir: "./tmp"
    max_file_size_mb: 45

  services:
    ytdl:
      enabled: true
      bin: "yt-dlp"
